proxy:
  secretToken: PROXY_TOKEN
  https:
    hosts:
      - jupyterhub.openlattice.com
    letsencrypt:
      contactEmail: "parthenon@openlattice.com"
singleuser:
  image:
    name: openlattice/jupyterhub-datascience
    tag: 0.0.7
  storage:
    type: "static"
    static:
      pvcName: "efs-persist"
      subPath: 'home/{username}'
  extraEnv:
    CHOWN_HOME: 'yes'
  uid: 0
  fsGid: 0
  lifecycleHooks:
    postStart:
      exec:
        command: ["pip", "install", "-e", "git+https://github.com/Lattice-Works/api-clients.git#egg=openlattice&subdirectory=python"]
  cmd: "start-singleuser.sh"
hub:
  extraEnv:
    AUTH0_SUBDOMAIN: "openlattice"
  extraConfig:
    myConfig.py: |
      from oauthenticator.auth0 import Auth0OAuthenticator
      c.LocalAuthenticator.create_system_users = True
      c.LocalAuthenticator.add_user_cmd = [
        'adduser', '-q', '--gecos', '""', '--disabled-password', '--force-badname'
      ]
      c.Auth0OAuthenticator.scope = ['openid', 'email', 'profile']
      c.Authenticator.auto_login = True
      c.Authenticator.admin_users = {
        'drew@openlattice.com',
        'matthew@openlattice.com'
      }

      """
      Custom Authenticator to use Auth0 OAuth with JupyterHub
      Derived using the Github and Google OAuthenticator implementations as examples.
      The following environment variables may be used for configuration:
          AUTH0_SUBDOMAIN - The subdomain for your Auth0 account
          OAUTH_CLIENT_ID - Your client id
          OAUTH_CLIENT_SECRET - Your client secret
          OAUTH_CALLBACK_URL - Your callback handler URL
      Additionally, if you are concerned about your secrets being exposed by
      an env dump(I know I am!) you can set the client_secret, client_id and
      oauth_callback_url directly on the config for Auth0OAuthenticator.
      """
auth:
  type: custom
  custom:
    className: oauthenticator.auth0.Auth0OAuthenticator
    config:
      client_id: ""
      client_secret: ""
      oauth_callback_url: "https://OAUTH_HOST/hub/oauth_callback"
